"""Render every Markdown resume in the corpus to a PDF.

    python scripts/build_resume_pdfs.py

**No model is called.** This is a deterministic Markdown-to-PDF renderer
built on reportlab: same input, same bytes out, zero API cost. The corpus
resumes were generated by a model once (scripts/generate_corpus.py); this
only changes their container so the web app can show a candidate the way
a recruiter would actually receive one.

Output goes to data/resume_pdfs/, one file per resume, same stem.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CORPUS = REPO / "data" / "synthetic_resumes"
OUT_DIR = REPO / "data" / "resume_pdfs"

_BOLD = re.compile(r"\*\*(.+?)\*\*")
_ITALIC = re.compile(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)")


def _inline(text: str) -> str:
    """Markdown emphasis -> reportlab markup, with XML escaped first.

    Order matters: escape before inserting tags, or a resume containing
    "R&D" or "C++ <-> Python" produces a document reportlab refuses to
    parse.
    """
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    text = _BOLD.sub(r"<b>\1</b>", text)
    return _ITALIC.sub(r"<i>\1</i>", text)


def build_pdf(markdown: str, destination: Path) -> None:
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import ListFlowable, ListItem, Paragraph, SimpleDocTemplate, Spacer

    body = ParagraphStyle(
        "body", fontName="Helvetica", fontSize=9.5, leading=13,
        alignment=TA_LEFT, spaceAfter=4,
    )
    name = ParagraphStyle(
        "name", parent=body, fontName="Helvetica-Bold", fontSize=17,
        leading=21, spaceAfter=2,
    )
    section = ParagraphStyle(
        "section", parent=body, fontName="Helvetica-Bold", fontSize=10,
        leading=13, spaceBefore=11, spaceAfter=5, textColor="#1a1a1a",
    )
    contact = ParagraphStyle("contact", parent=body, fontSize=9, textColor="#555555")

    flowables = []
    bullets: list = []

    def flush_bullets() -> None:
        if bullets:
            flowables.append(
                ListFlowable(
                    list(bullets), bulletType="bullet", start="•",
                    leftIndent=14, bulletFontSize=7, spaceAfter=5,
                )
            )
            bullets.clear()

    seen_heading = False
    for raw in markdown.splitlines():
        line = raw.rstrip()
        if not line.strip():
            flush_bullets()
            continue

        if line.startswith("# "):
            flush_bullets()
            flowables.append(Paragraph(_inline(line[2:]), name))
            seen_heading = True
        elif line.startswith("## "):
            flush_bullets()
            flowables.append(Paragraph(_inline(line[3:]).upper(), section))
            seen_heading = True
        elif line.startswith("### "):
            flush_bullets()
            flowables.append(Paragraph(_inline(line[4:]), section))
            seen_heading = True
        elif line.lstrip().startswith(("- ", "* ")):
            bullets.append(ListItem(Paragraph(_inline(line.lstrip()[2:]), body), leftIndent=14))
        else:
            flush_bullets()
            # The contact block sits above the first heading and reads
            # better small and grey, the way a real resume prints it.
            flowables.append(Paragraph(_inline(line), body if seen_heading else contact))

    flush_bullets()
    if not flowables:
        flowables.append(Paragraph("(empty resume)", body))
    flowables.append(Spacer(1, 0.1 * inch))

    destination.parent.mkdir(parents=True, exist_ok=True)
    SimpleDocTemplate(
        str(destination), pagesize=LETTER,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
        topMargin=0.7 * inch, bottomMargin=0.7 * inch,
        title=destination.stem, author="synthetic corpus",
    ).build(flowables)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true", help="rebuild PDFs that already exist")
    args = parser.parse_args()

    try:
        import reportlab  # noqa: F401
    except ImportError:
        print(
            "reportlab is not installed. It is an optional extra because only "
            "this script needs it:\n\n    pip install -e \".[pdf]\"\n",
            file=sys.stderr,
        )
        return 2

    sources = sorted(CORPUS.glob("*.md"))
    if not sources:
        print(f"No resumes in {CORPUS}", file=sys.stderr)
        return 2

    built = skipped = 0
    for source in sources:
        destination = OUT_DIR / f"{source.stem}.pdf"
        if destination.exists() and not args.force:
            skipped += 1
            continue
        build_pdf(source.read_text(encoding="utf-8"), destination)
        built += 1

    print(f"Built {built} PDF(s), skipped {skipped} already present -> {OUT_DIR.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
